# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IN1', models.IntegerField(default=0)),
                ('IN2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnalogOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AOUT1', models.IntegerField(default=0)),
                ('AOUT2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mac_address', models.CharField(default='0xFFFFFF', max_length=128)),
                ('location', models.CharField(max_length=64)),
                ('address', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(max_length=256)),
                ('lift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IN1', models.BooleanField(default=False)),
                ('IN2', models.BooleanField(default=False)),
                ('IN3', models.BooleanField(default=False)),
                ('IN4', models.BooleanField(default=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OUT1', models.BooleanField(default=False)),
                ('OUT2', models.BooleanField(default=False)),
                ('OUT3', models.BooleanField(default=False)),
                ('OUT4', models.BooleanField(default=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A0', models.BooleanField(default=False)),
                ('A1', models.BooleanField(default=False)),
                ('A2', models.BooleanField(default=False)),
                ('A3', models.BooleanField(default=False)),
                ('A4', models.BooleanField(default=False)),
                ('A5', models.BooleanField(default=False)),
                ('A6', models.BooleanField(default=False)),
                ('A7', models.BooleanField(default=False)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enable_control', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.CharField(max_length=100)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.CharField(max_length=100)),
                ('api_url', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Device')),
            ],
        ),
        migrations.AddField(
            model_name='analogoutput',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Device'),
        ),
        migrations.AddField(
            model_name='analoginput',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='v1.Device'),
        ),
    ]
