# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analoginput',
            old_name='IN1',
            new_name='AIN1',
        ),
        migrations.RenameField(
            model_name='analoginput',
            old_name='IN2',
            new_name='AIN2',
        ),
        migrations.RenameField(
            model_name='digitalinput',
            old_name='IN1',
            new_name='DIN1',
        ),
        migrations.RenameField(
            model_name='digitalinput',
            old_name='IN2',
            new_name='DIN2',
        ),
        migrations.RenameField(
            model_name='digitalinput',
            old_name='IN3',
            new_name='DIN3',
        ),
        migrations.RenameField(
            model_name='digitalinput',
            old_name='IN4',
            new_name='DIN4',
        ),
        migrations.RenameField(
            model_name='digitaloutput',
            old_name='OUT1',
            new_name='DOUT1',
        ),
        migrations.RenameField(
            model_name='digitaloutput',
            old_name='OUT2',
            new_name='DOUT2',
        ),
        migrations.RenameField(
            model_name='digitaloutput',
            old_name='OUT3',
            new_name='DOUT3',
        ),
        migrations.RenameField(
            model_name='digitaloutput',
            old_name='OUT4',
            new_name='DOUT4',
        ),
    ]
