# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20170322_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicetoken',
            old_name='lift',
            new_name='device',
        ),
    ]
